server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:1211/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "XaajYDn1bZABaTE0YeJNDy6ZyU5pRKsy+tF5l45+q4F+/RpVqZjclXWqWw9BC6G"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in seconds